### ISSUE TITLE
UI: CRUD for Datasources

### ISSUE THREAD

**Issue by AntoineThebaud** [perses/perses#1033]
Add the necessary screens & forms to be able to create, read, update and delete datasources from the UI.

Notable difference with e.g dashboards, a datasource can be created a 3 different levels (global, project and dashboard).

**Comment by AntoineThebaud** [comment]
Current status:
- Project datasources CRUD to be tackled with https://github.com/perses/perses/pull/1282.
- Global datasources CRUD to be tackled with https://github.com/perses/perses/pull/1319.
- Local datasources CRUD still to be done.

**Comment by celian-garcia** [comment]
@AntoineThebaud I took the liberty to update your status comment with the last PR. 
This PR, when done, should close this issue. If you think of something that I missed tell me!

**Comment by AntoineThebaud** [comment]
Hmm I think your PR tackles something different, by Local Datasources CRUD I meant having access to the create/edit datasource form for the local/dashboard datasources, just like we have for dashboard variables.

**Comment by celian-garcia** [comment]
oh yes okay! I forgot that. Let me remove my edit and change the closes to relates

**Comment by AntoineThebaud** [comment]
No worries, this is something we also forgot upstream when we planned the activities for this summer 😅
