### ISSUE TITLE
Join UI forces with https://github.com/savecost/datav

### ISSUE THREAD

**Issue by bwplotka** [perses/perses#111]
Accidently found datav project out there, which looks really promising in terms of UI. Wonder if we could reach them and join forces on dashboarding.

**Comment by Nexucis** [comment]
Hey @bwplotka :).

Thank you for sharing your deep walking in Github around this topic ! 

Isn't something you already found and checked @juliusv ? I think I recognized a bit the project.
Do you remember what was the outcome of this check ?

**Comment by juliusv** [comment]
The aims, scope, and underlying tech of datav seem quite different to Perses: "Datav is built in GO、RUST and Clickhouse, so it's lightning fast." (https://github.com/savecost/datav).

Datav includes a whole observability pipeline based on Clickhouse and wants to do way more on the UI side as well. Whereas Perses wants to be just a light-weight dashboard viewer/builder with a Gitops-first approach, while still supporting a multitude of datasources in the end. Datav also seems to be based largely on a fork of Grafana code for its UI, which we want to avoid.

**Comment by Nexucis** [comment]
I think we can close this issue.
Thanks for raising the point @bwplotka that was interesting for sure. Feel free to reopen this issue if you feel we should keep it open
