### ISSUE TITLE
Build core Table panel

### ISSUE THREAD

**Issue by sjcobb** [perses/perses#1143]
~~Planning to use MUI DataGrid~~ See Julie [comment here](https://github.com/perses/perses/issues/1143#issuecomment-1536502677) about library decision

Mockups TBD

**Comment by nicolastakashi** [comment]
Another nice Datagrid is mui-datatables
With some built-in feature such as searching and filtering

**Comment by sjcobb** [comment]
> Another nice Datagrid is mui-datatables
> With some built-in feature such as searching and filtering

Thanks! @juliepagano can’t remember if you mentioned this one before, but it does look interesting: https://github.com/gregnb/mui-datatables

**Comment by nicolastakashi** [comment]
@sjcobb I tried the MUI Datagrid and this is good, but on the free version, there are some limitations in my view.

- Can't disable paging (Some users may prefer not to use pagination)
- Can't filter for multiple columns

**Comment by juliepagano** [comment]
> https://github.com/gregnb/mui-datatables

Can you get their demo link to load for you? I briefly looked at the github a couple days ago, but couldn't get the demo link to load (still can't). It's not a dealbreaker, but not being able to look at the demos didn't excite me about digging into it a ton more.

I was planning to start with [tanstack table](https://tanstack.com/table/v8) (headless table lib) combined with MUI to see if I could get something there relatively quick and then also compare with a few other non-headless table implementations.

**Comment by nicolastakashi** [comment]
There's a code sandbox on their readme page, https://codesandbox.io/s/github/gregnb/mui-datatables?file=/src/index.js:0-42
BTW Thanks for sharing, interesting this tanstack table.

**Comment by juliepagano** [comment]
[This issue](https://github.com/gregnb/mui-datatables/issues/2003) related to why the web site isn't working also makes me a little wary of picking up that library. Will take a closer look at the code sandbox and feature set though to compare the feature set.

**Comment by Gladorme** [comment]
I think Tanstack Table query is the best option.
It has all MUI X Datagrid free features and almost all the paid one.
We can design tables as we want. It may took a little more time to create standard components as pagination / sorting menu, but we are not limited 😄 
Bonus: it is well maintained + prod ready (it used by Grafana for their tables too).

**Comment by celian-garcia** [comment]
Considering the work done by @Gladorme on the table in v0.47 and the improvements of v0.48. I think we can definitely consider this issue as closed. 
Thanks <3
