### ISSUE TITLE
Invalid variables throw opaque 500 Internal Server Error

### ISSUE THREAD

**Issue by sjcobb** [perses/perses#1157]
While working on saving default variables and time range, I've noticed that while invalid panels throw _great_ errors (now that Issue #960 has been fixed), the errors for invalid variables in our UI are unhelpful.

One example is I accidentally added two variables with the name 'interval' and in the UI, I get a blank screen and a '500 (Internal Server Error)' 

It looks like a better error is thrown if checking logs: 
`ERRO[2023-05-09T13:04:12-04:00] unexpected error not handle  - error="variable \"interval\" (index 1) already exists"`

Is it possible to propagate this error to the UI?

Also related to Matrix discussion [here](https://matrix.to/#/!XNmgYIAndZOkEvQAbb:matrix.org/$RTjoXbt37sena8G7PxjMSAOAWtFZwFMnMvu2Kj24lbc?via=matrix.org&via=herail.net).

## Details
<img width="1447" alt="image" src="https://github.com/perses/perses/assets/9369625/fb18b59f-6af7-460b-82fd-8c3a475f29b4">

```json
{
  "kind": "Dashboard",
  "metadata": {
    "name": "Defaults",
    "created_at": "2022-12-21T00:00:00Z",
    "updated_at": "2023-02-07T00:28:57.658905Z",
    "version": 1,
    "project": "testing"
  },
  "spec": {
    "duration": "1h",
    "variables": [
      {
        "kind": "ListVariable",
        "spec": {
          "name": "interval",
          "default_value": "5m",
          "allow_all_value": false,
          "allow_multiple": false,
          "plugin": {
            "kind": "StaticListVariable",
            "spec": { "values": ["1m", "5m"] }
          }
        }
      },
      {
        "kind": "ListVariable",
        "spec": {
          "name": "interval",
          "allow_multiple": false,
          "allow_all_value": false,
          "plugin": {
            "kind": "StaticListVariable",
            "spec": {
              "values": [
                {
                  "value": "1m",
                  "label": "1m"
                },
                {
                  "value": "5m",
                  "label": "5m"
                }
              ]
            }
          }
        }
      },
      {
        "kind": "ListVariable",
        "spec": {
          "name": "NewListVariable",
          "display": { "name": "Test display name", "hidden": false },
          "default_value": "second value",
          "allow_all_value": true,
          "allow_multiple": false,
          "plugin": {
            "kind": "StaticListVariable",
            "spec": {
              "values": [
                { "label": "test list value", "value": "test list value" },
                { "label": "second value", "value": "second value" },
                {
                  "label": "another list value",
                  "value": "another list value"
                },
                { "label": "final value", "value": "final value" }
              ]
            }
          }
        }
      }
    ],
    "panels": {
      "markdownEx": {
        "kind": "Panel",
        "spec": {
          "display": {
            "name": "Markdown Example Zero",
            "description": "This is a markdown panel"
          },
          "plugin": { "kind": "Markdown", "spec": { "text": "## Example" } }
        }
      }
    },
    "layouts": [
      {
        "kind": "Grid",
        "spec": {
          "display": { "title": "Row 1", "collapse": { "open": true } },
          "items": [
            {
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "content": { "$ref": "#/spec/panels/markdownEx" }
            }
          ]
        }
      }
    ]
  }
}

```

**Comment by Nexucis** [comment]
> One example is I accidentally added two variables with the name 'interval'

Did you modify the JSON when you added these two variables ?

**Comment by Nexucis** [comment]
I mean did you modify directly the files in the database, or did you add it through the UI.
I'm asking that because it's not the same flow. And I am pretty sure if you modify anything in the JSON file directly in the database and you break a panel for example, the error will be the same: "500 Internal Server Error" which is the accurate error the server need to forward since the User cannot do anything against that. (Because the database is corrupted).

And when we are talking about internal stuff in the server, yes the erreur must be opac because otherwise it could show some security issue the server might have.

**Comment by sjcobb** [comment]
Hey sorry for the delay here @Nexucis!
Yeah, I guess this was another instance of me doing this during local development. 🙃

I do think this could happen organically though to users when we push out breaking changes (this happened to me after the recent queries breaking change) and it can be difficult to figure out which dashboard is broken. And then which part of that dashboard (which specific panel, variables, etc.). 

IMO we do really need to start thinking through our options for #1186 - how we’ll handle schema versioning and upgrades especially if we’re limited with the errors that can be thrown in these cases

**Comment by celian-garcia** [comment]
My two cent here : There shouldn't be any production use case where people modify the database directly. Even if the database is a file system. That's why grafana have the provisioner in place. You define the resources that should be injected on start through provisioner, and if a syntax error occurs, or a migration is needed, you see it at this moment. 

The versioning is important but implementing a provisioning mechanism is the right solution if we foresee such a usecase.
