### ISSUE TITLE
Switching between dark and light theme should not reload dashboard

### ISSUE THREAD

**Issue by sjcobb** [perses/perses#1173]
Theme toggle currently causes all queries to fire again

**Comment by sjcobb** [comment]
> Theme toggle cause a complete page reload. Because of this [line](https://github.com/perses/perses/blob/28aa09f49312df68750926c40ac68cf3de2736ae/ui/app/src/context/DarkMode.tsx#L46)

Yeah I remember [trying to remove that line](https://github.com/perses/perses/pull/415#issuecomment-1108909667) and it required some further refactoring. I just never had a chance to go back and look more into it (the entire dark mode implementation could really be simplified)

**Comment by nicolastakashi** [comment]
I would like to work on this @sjcobb
