### ISSUE TITLE
Support Auto Refresh

### ISSUE THREAD

**Issue by eunicorn** [perses/perses#1213]
It would be nice to have the ability to refresh charts automatically given an interval. Thinking maybe there should be a dropdown component (mui select component) next to the refresh button where you can select the interval (similar to grafana). 

The url query params should also be updated the refresh interval, and this will probably add a new field to the dashboard json schema.

**Comment by nicolastakashi** [comment]
Hey @eunicorn can you assign this to me?

**Comment by eunicorn** [comment]
@nicolastakashi Might be helpful to look at https://github.com/perses/perses/blob/main/ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx. I think you can probably just use the same `refresh` function there for auto refresh

**Comment by sjcobb** [comment]
For the timing of calling refresh, I think react-query has ability to customize `refetchInterval` that’d be good to try out
