### ISSUE TITLE
Overriden project variable does not hide correct variable in dashboard toolbar

### ISSUE THREAD

**Issue by sjcobb** [perses/perses#1338]
Tried using shortcut to hide a project variable and it didn't hide the variable in the dashboard toolbar that I was expecting.

Bug example:

https://github.com/perses/perses/assets/9369625/4a1c80f9-9a8b-4b01-9337-4d14843b5de1

**Comment by sjcobb** [comment]
@celian-garcia not sure if I was doing something wrong but overriding a project variable has unexpected behavior

**Comment by celian-garcia** [comment]
You need to toggle off the visibility to hide variable. Or I don´t understand the problem

**Comment by sjcobb** [comment]
Whoops not sure how I forgot, sorry about that @celian-garcia 😅
