### ISSUE TITLE
Choose a validation lib and use it to make basic validation on each form

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#1348]
From the discussion we had with @sjcobb @Gladorme, best candidates for now seems to be a conjunction of https://react-hook-form.com/ + https://zod.dev/

**Comment by celian-garcia** [comment]
From the discussion we had with @sjcobb @Gladorme, best candidates for now seems to be a conjunction of https://react-hook-form.com/ + https://zod.dev/

**Comment by sjcobb** [comment]
Yes, let’s start experimenting with this asap and agreed that the libs in description seem like top candidates

**Comment by Gladorme** [comment]
All big forms are validated by Zod and React-Hook-Form (#2044), except for plugin spec inputs. It still need to be done. However, plugin should be able to inject their validation schema in the ValidationProvider in order to have full validation.
