### ISSUE TITLE
password_file configuration input

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#1368]
### Proposal

Trying to copy paste some part of the helm chart in a production like environment, I realize that the database.sql.password from configuration file is unsafe to me. ~Because the config map is often more accessible by people, than the file itself or an environment variable inside the pod.~ Edit: Okay this a secret my bad

Either we set the password as an environment variable in the helm chart
Or we can propose a new configuration field password_file which is quite standards nowadays.
Or both.

With all the changes it requires in the chart/code. 

---
**Edit**: Quick summary from the comments below

### Into the backend code:
- A new ``database.sql.password_file`` configuration field

### Into the helm chart:
- Change config.yaml to be a configmap
- Create a dedicated secret to populate the password in a file and password_file configuration
- For people that have their own secret they should be able to provide their own secret

**Comment by nicolastakashi** [comment]
@celian-garcia currently the config is `secret` and not a `configmap`, but I'm fine providing this as env var, we just need to bear in mind that env var secrets are usually considered high severity issues by software such as StackRox.

**Comment by celian-garcia** [comment]
Ah okay I've been tricked by the name of the file. Yeah I think we should separate what is configuration from what is secret. In some organizations, you can have the need to see the config but not have access to secrets. 

Indeed the safer approach is probably the password_file as everyone does

**Comment by nicolastakashi** [comment]
Yeah, I agree with you.
Today the entire config is coupled so this was the reason I built it as a secret, since we need inject some secret information, But having the password_file as an option we can move it between configmap and secret.

**Comment by celian-garcia** [comment]
So to be crystal clear, the required changes would be : 
- in the code: 
  - A new password_file configuration field
- in the chart: 
  - Change config.yaml to be a configmap
  - Create a dedicated secret to populate the password in a file and password_file configuration
Does this sound correct to you?

This is always complicate to create reusable helm charts as every company have its own tooling and requirements.
Anyway there is no emergency but at some point it will be asked. So let's keep it there to not forget.

**Comment by nicolastakashi** [comment]
It seems really a good plan.
We just need to ensure we provide either a secret either a secret name to the ones provide existing secret.

**Comment by celian-garcia** [comment]
Is this closed by this ? https://github.com/perses/helm-charts/pull/5
