### ISSUE TITLE
1:244: parse error: missing unit character in duration

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#1370]
### What did you do?

I imported the dashboard Node Exporter Full coming from Grafana 

### What did you expect to see?

No error

### What did you see instead? Under which circumstances?

![image](https://github.com/perses/perses/assets/10258608/97fd0c8c-c161-405e-bbd7-f7f375c79de9)

**Comment by Gladorme** [comment]
`$__interval` is not computed, so Prometheus is not happy (should be fixed soon). However, it could be interesting to display the query too. It will be easier to debug in the future 😄
