### ISSUE TITLE
Filter variable list selection with a search field

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#1381]
### Proposal

Would be good to be able to filter a bit the selection that we are doing in a variable typing some prefix or something. It would help to reduce the big lists.

Suggestion? 
https://mui.com/material-ui/react-autocomplete/#combo-box

**Comment by AntoineThebaud** [comment]
This was implemented with #1576. The UX could still be improved with e.g checkboxes, but that's worth a dedicated issue.
