### ISSUE TITLE
How do I connect to the prometheus URL on localhost:9090?

### ISSUE THREAD

**Issue by capttrousers** [perses/perses#1417]
### What did you do?

I tried the main prom url when configuring the datasource: `http://localhost:9090`

Perses is running with docker as is prometheus, and both are using host networking:
```
docker run -d \
        --name perses \
	--network="host" \
	persesdev/perses
```

### What did you expect to see?

Data

### What did you see instead? Under which circumstances?

I get this error when trying to add a panel with a simple promql query `node_disk_usage_level_1_bytes`
```
NetworkError when attempting to fetch resource.
```

### System information

Linux 6.1.21-v8+ aarch64

### Perses version

0.39.0

### Logs

```text
Dont know where to get logs, `docker logs perses` just shows the initial welcome lines
```

**Comment by Nexucis** [comment]
Hello,

I would say it depends if you are setting up a proxy configuration in the datasource. If it's the case, the URL wouldn't be http://host:9090 ?
Otherwise, if you are using a direct url, and therefore it will be the UI that would perform the request and not the backend, then http://localhost:9090 should work yes.

By default the level of the logs are at the `error` level. Can be useful to decrease to `info` or `debug`

**Comment by capttrousers** [comment]
Thanks for the quick response, there shouldnt be a proxy involved, the perses docker container should be able to reach the prometheus docker container since they're both using host networking. 

I'm not able to exec into the perses docker container to verify it can reach prometheus on that url though:

```
docker exec -it perses sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
```

How do I set the loglevel?

**Comment by Nexucis** [comment]
you can try the debug image : `persesdev/perses:latest-debug` that contains a shell.

When I was talking about a proxy, I wasn't talking about a proxy in the docker configuration. The Perses API can be able to be a proxy for the UI and contact the different datasource such as Prometheus for the UI.
To do that, you can specify in the datasource configuration that you want to use a proxy (i.e. how the Perses backend can contact the datasource server, here prometheus)

The loglevel can be set using the flag `--log.level=error` . Not that if you override the CMD, you will need to set as well the config path which is by default `"--config=/etc/perses/config.yaml"`: https://github.com/perses/perses/blob/main/Dockerfile#L25

**Comment by capttrousers** [comment]
Ah gotcha, now I understand the Proxy config option for setting up a datasource. 

Using the localhost:9090 url for the proxy config worked. I also tried the Direct Access option using the IP of the host machine and that works too, I think because you're saying the Direct Access option queries the prometheus DB directly from the browser (UI client) so localhost there would only work if prometheus is running on your machine.

Thanks!
