### ISSUE TITLE
Constantly increasing memory usage

### ISSUE THREAD

**Issue by zix99** [perses/perses#1440]
### What did you do?

I have setup perses via the docker image (per described in the readme), and connected it to my prometheus instance.  I have a few dashboards and widgets (including one of the attached image).

### What did you expect to see?

Memory should remain relatively flat or exhibit GC-collection saw-tooth form.

### What did you see instead? Under which circumstances?

Perses memory consistently increases over time, even when not being used.  Eventually the docker image crashes (when it hits its memory limit, which I have set at 128 MB).

![image](https://github.com/perses/perses/assets/1558302/fddb188c-0e11-479c-be8e-4a397942fd70)

The green line reset sooner because I switched it from 0.39 to 0.40 to see if that would help.

### System information

linux amd64 (docker)

### Perses version

0.39 and 0.40

### Perses configuration file

```yaml
Default for the docker file
```

**Comment by Nexucis** [comment]
Thank you for reporting this memory leak !
We are working on it and will certainly release a hot fix soon.

**Comment by Nexucis** [comment]
@zix99 we just created a patch (v0.40.1) that contains the fix for the memory issue.
