### ISSUE TITLE
Prometheus Instant Query Support

### ISSUE THREAD

**Issue by nicolastakashi** [perses/perses#1456]
### Proposal

Currently, Perses only supports Prometheus Range Queries as part as the Explore Page and other on going discussions around the Perses ecosystem, we should provide the Instant Query capability.

## Dependencies

- [x] https://github.com/perses/perses/issues/1303

**Comment by celian-garcia** [comment]
For reference, here is what would remain after this PR to consider the Prometheus Instant query is fully supported (be able to use it in all timeseries panels with a switch or something)
https://github.com/perses/perses/pull/1982#discussion_r1596726647

**Comment by Nexucis** [comment]
> Just putting back porting my comment I made in the PR linked: 

I don't think it's a good idea to mixed panel in the same plugin.

What would be the benefit of doing that ? Excepting in an explorer mode, I don't see why in a dashboard you would need to switch from a range query to an instant query.

**Comment by celian-garcia** [comment]
> back porting my answer ^^

This might be not useful in TimeSeriesChart yes, or at least I don't have an idea of the use case. But when you do use a gauge chart for example. You may want to have the choice between using a range query and display the average/last/min etc or make an instant query that would be more performant if you know you want the last.

**Comment by celian-garcia** [comment]
I'm closing this issue as from the original description, the capability to make instant query is technically there now. Thanks to the supported query field and the "mode" instant or range, a plugin developer can make a switch if needed, putting the "mode" value in the panel specs if it needs to be saved
