### ISSUE TITLE
percli support directories on apply cmd

### ISSUE THREAD

**Issue by nicolastakashi** [perses/perses#1464]
### Proposal

Since the Perses docker image is a distroless docker image, we don't have the ability to use `extglob` and run command like that `/bin/percli apply -f datasource/*.json`.

Given this limitation, would be awesome if `percli` supports directories on the `apply` command.

**Comment by Nexucis** [comment]
as a side note, it should help to finish this PR: https://github.com/perses/helm-charts/pull/8
