### ISSUE TITLE
Dashboard search in navbar

### ISSUE THREAD

**Issue by AntoineThebaud** [perses/perses#1532]
### Proposal

Today we have a search bar on the home page that does fuzzy search through all dashboards of all projects. It would probably be convenient to have the same search bar integrated into the top navbar, so that it's available on any screen of Perses.

**Comment by AntoineThebaud** [comment]
Additionally we could consider searching & returning other types of resources with this search (projects, datasources, sub-folders when we'll have them, etc)

**Comment by Nexucis** [comment]
this issue has been solved with #2090
