### ISSUE TITLE
Import dashboard as JSON from UI

### ISSUE THREAD

**Issue by AntoineThebaud** [perses/perses#1533]
### Proposal

Currently we can import Perses dashboards in JSON format using the CLI, or via provisioning (https://github.com/perses/perses/pull/1486). It would be great to permit such JSON import from the UI too.

NB: bonus task: since we already have the possiblity to import Grafana dashboard in JSON via the migrate feature, we could imagine having a single input for pasting JSON & Perses would be able to guess on the fly if this is a Perses dashboard (= simply import) or a Grafana dashboard (= migrate + import).

**Comment by AntoineThebaud** [comment]
Could be tackled as part of the proposed [dashboard creation flow overhaul](https://github.com/perses/perses/discussions/1274)

**Comment by Nexucis** [comment]
this has been tackled with https://github.com/perses/perses/pull/1769
