### ISSUE TITLE
Add documentation website

### ISSUE THREAD

**Issue by AntoineThebaud** [perses/perses#1535]
### Proposal

Publish the docs we have currently in the [docs](../tree/main/docs) folder to a proper, dedicated website.

As suggested by @Nexucis this website should probably aggregate docs coming from this repo + other Perses repos like helm chart docs or operator docs.

**Comment by AntoineThebaud** [comment]
Was actually tackled a while ago as part of the work on https://github.com/perses/website repo.

Perses documentation available at https://perses.dev.

**Comment by mgnisia** [comment]
Hi! Just opened this issue for the reference: https://github.com/perses/website/issues/162, let me know if I can support somehow.
