### ISSUE TITLE
Variable going crazy after grafana migration

### ISSUE THREAD

**Issue by AntoineThebaud** [perses/perses#1552]
### Context

I encountered a case with a specific dashboard where doing grafana migration will cause to have some variables recomputing endlessly.

See video:

https://github.com/perses/perses/assets/7058693/d5281d4c-ebc3-4c25-b874-9896e4ab696a

These 2 variables have in common that they are relying on a query that uses `$__range` as time range argument to a promQL function. If I replace these by hardcoded timeranges, the issue stops. See video:

https://github.com/perses/perses/assets/7058693/1cf95aeb-3ed0-45c3-8d8b-0209b6d399d8

I didnt time to check if the same is happening with a dashboard created from scratch, but I don't expect this to be linked with the fact this is a migrated dashboard. However maybe the issue is happening only when you have a quite big amount of data queried behind the scenes? (Which is the case in the example provided).

### Perses version

main-2023-10-26-d44ceabd

**Comment by Gladorme** [comment]
I am checking if I can fix the issue. For now, I see that if you close all group panels of the dashboard, it's stopping the issue 🤔
