### ISSUE TITLE
On Mac api_backend_dev startup throws DS_Store errors

### ISSUE THREAD

**Issue by sjcobb** [perses/perses#1586]
### What did you do?

Ran startup: `./scripts/api_backend_dev.sh --override`

### What did you expect to see?

Backend should start without errors
Similar PR from before: https://github.com/perses/perses/pull/1285

### What did you see instead? Under which circumstances?

Errors:
```
Plugin .DS_Store will not be loaded: it is not a folder
WARN[0065] Plugin .DS_Store will not be loaded: it is not a folder
```

### System information

Mac (M1 - Ventura 13.5.1)

### Perses version

0.41.1

### Perses configuration file

```yaml
Default config
```

**Comment by sjcobb** [comment]
@Nexucis @AntoineThebaud Do I need to do anything different to get the BE working after the [security changes](https://github.com/perses/perses/pull/1560), if so, is that documented anywhere?

**Comment by Nexucis** [comment]
@sjcobb since we add the provisioning feature: https://github.com/perses/perses/pull/1486/files#diff-0a68894bb3ceab5affe56cf6b15947ecb6a022e999d9a711ac15d75d68b8b1b9, the creation of the local database doesn't use a script.
It is done when Perses is running.

So hopefully just running `./scripts/api_backend_dev.sh`  should work. (the flag `--override` doesn't exist anymore)

**Comment by Nexucis** [comment]
and by looking at the logs you shared, it looks like it is just a warning and not an error. So hopefully the backend should have started right ?

**Comment by sjcobb** [comment]
> and by looking at the logs you shared, it looks like it is just a warning and not an error. So hopefully the backend should have started right ?

Nah I couldn’t get the backend to start but yeahh, must not be related to that warning, I’ll try again without override and might just wipe my environment and start over—I think I have some old leftover gitignored code that might be causing issues
