### ISSUE TITLE
Make RoleBinding subjects case insensitive

### ISSUE THREAD

**Issue by Gladorme** [perses/perses#1721]
### What did you do?

Currently resources name are case insensitive. But not the RBAC cache.
If you have an user "Toto" and you have a role binding with subject: "toto".

### What did you expect to see?

It should have binded role to "Toto"

### What did you see instead? Under which circumstances?

"Toto" do not have the role binded

### Perses version

0.43.0

**Comment by Nexucis** [comment]
Correction: the system is actually case sensitive today. There is nothing in the code that lowercase the IDs
