### ISSUE TITLE
percli apply should not accept silently a different project in the json and in the -p

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#1917]
### What did you do?

Create a dashboard-with-project-b.json with project ProjectB
Run ``percli apply -d dashboard-with-project-b.json -p ProjectA``

### What did you expect to see?

I would expect an error saying that the projects are not aligned.

We could say that the project from the context takes precedence but it can be confusing if the project `ProjectA` is already saved in the context file and we do ``percli apply -f dashboard-with-project-b.json`` it would save in `ProjectA`. This is not better.

### What did you see instead? Under which circumstances?

Currently this is silently creating/updating the dashboard in the **ProjectB** (the one from the json file)

### Perses version

0.44.0

**Comment by ying-jeanne** [comment]
hi @celian-garcia i opened a tantative PR regard this bug, if you could take a look. Thank you.
