### ISSUE TITLE
Dashboards auto-refresh not working

### ISSUE THREAD

**Issue by karsov** [perses/perses#1931]
### What did you do?

I first noticed it on a Docker Compose setup I'm doing locally (Perses Docker image 0.44), but you can see it too in the "Node Exporter Full" dashboard at [demo.perses.dev](http://demo.perses.dev/).

What happens is that the dashboards is indeed redrawn every refresh interval, however the PromQL queries' `start` and `end` times are not changed, so effectively nothing changes on the screen (apart from a visible blink).

If I explicitly click the "refresh" button it works, and also if I change the refresh interval it updates the charts.

### What did you expect to see?

I expect that the charts update their data at every refresh interval.

### What did you see instead? Under which circumstances?

The charts do not change on an auto refresh (although the dashboard is re-drawn).

### Perses version

0.44

**Comment by celian-garcia** [comment]
@Nexucis @Gladorme this issue is fixed right ?

**Comment by Nexucis** [comment]
yup just need to merge back the fix in the main branch to close this issue

**Comment by karsov** [comment]
I can confirm that with Perses 0.45 the auto-refresh is working.
Thanks!
