### ISSUE TITLE
Can't log in to provisioned users

### ISSUE THREAD

**Issue by sinkingpoint** [perses/perses#1960]
### What did you do?

1. Clone the repo
2. Start the UI with `npm run start`
3. Start the backend with `./scripts/api_backend_dev.sh`
4. Access Perses at localhost:3000
5. Try to log in with username: `admin`, password: `password`
6. Observe that the log in fails

### What did you expect to see?

I should be able to log in

### What did you see instead? Under which circumstances?

![image](https://github.com/perses/perses/assets/4386405/e0002e0c-c0ba-4c27-bb9d-7495ebd726ec)

### Perses version

0.44.0

### Logs

```text
INFO[2024-04-27T16:30:05+10:00]                                               method=POST status=400 uri=/api/auth/providers/native/login
WARN[2024-04-27T16:30:19+10:00] password do not match                         error="crypto/bcrypt: hashedPassword is not the hash of the given password"
```
```

**Comment by sinkingpoint** [comment]
`git bisect` tracks this back to 9ed2bce5c1df357e1f57b68670539665639eb620 

What seems to be happening is that we call `Create`, which [sets the password to the password hash in the entity](https://github.com/perses/perses/blob/main/internal/api/impl/v1/user/service.go#L51), but the call to [`Create`](https://github.com/perses/perses/blob/main/internal/api/impl/v1/user/service.go#L52) fails [because the file exists](https://github.com/perses/perses/blob/main/internal/api/database/file/file.go#L75). That error gets propagated through to the provisioning system [which then falls back to trying to `Update` the User](https://github.com/perses/perses/blob/main/internal/api/provisioning/provisioning.go#L89-L93), but `Update` [rehashes](https://github.com/perses/perses/blob/main/internal/api/impl/v1/user/service.go#L71-L76) the password resulting in the password for the user being set to the hash of the actual password. 

Prior to 9ed2bce5c1df357e1f57b68670539665639eb620 , the logic when provisioning was to do a `Get` on the service. If the get succeeded then we called the `Update` function, otherwise we called the `Create` function. After that commit, then logic is to call the `Create` function and let that tell us if the entity exists. In the user case though, `Create` modifies the resource so this breaks

**Comment by celian-garcia** [comment]
@sinkingpoint @Nexucis I think this one is fixed right ?

**Comment by Nexucis** [comment]
yup just need to merge back the fix in the main branch to close this issue
