### ISSUE TITLE
GaugeChart: wrong background color in dark theme

### ISSUE THREAD

**Issue by AntoineThebaud** [perses/perses#2011]
### What did you do?

- Have a Gauge chart on a dashboard.
- UI theme set on dark.

### What did you expect to see?

With dark theme, the background color of the gauge should be close to the panel background color (thus sth like dark gray), just like it is in white them (light gray vs white)

### What did you see instead? Under which circumstances?

The background is the same as in white theme (= lightgray)
![image](https://github.com/perses/perses/assets/7058693/97c2f668-57d0-4ad3-8080-2c0f1929d960)
vs with white theme:
![image](https://github.com/perses/perses/assets/7058693/a3b3a4c4-5de1-4952-8076-83f89984e6c1)

### Perses version

0.45.0

**Comment by celian-garcia** [comment]
good first issue ?

**Comment by Gladorme** [comment]
![image](https://github.com/perses/perses/assets/5657041/80e9db0c-2800-44bf-bbc2-9cc410c74904)
![image](https://github.com/perses/perses/assets/5657041/32de75c0-fa11-435b-afec-ce43ec184038)
I have a quick win if it's good for you
