### ISSUE TITLE
Pie charts

### ISSUE THREAD

**Issue by tristanmorgan** [perses/perses#2022]
### Proposal

Would it be possible to have data viewed as a pie chart?

and example would be taking a query like `count by (version)(go_info)` to see what portion of services are running older golang versions.

**Comment by AntoineThebaud** [comment]
FYI we are not likely to tackle this kind of feature until the new plugin architecture is in place. You can track the latter by following https://github.com/perses/perses/issues/1543.

**Comment by sjcobb** [comment]
When this does get picked up later, it'll be possible to extend the existing [BarChart implementation](https://github.com/perses/perses/blob/main/ui/components/src/BarChart/BarChart.tsx#L78) to become a pie chart, that is built using ECharts [dataset](https://apache.github.io/echarts-handbook/en/concepts/dataset/#define-data-in-dataset) ([example](https://echarts.apache.org/examples/en/editor.html?c=dataset-link)) which makes it easier to switch between series types

**Comment by zhuje** [comment]
Hi everyone! The Red Hat team is working on creating the pie chart. We're creating it in the current architecture and will convert it to the new plugin architecture once that is finalized.

**Comment by Nexucis** [comment]
Pie Chart has been implemented through https://github.com/perses/perses/pull/2170
