### ISSUE TITLE
Clarify positioning and intention

### ISSUE THREAD

**Issue by agardnerIT** [perses/perses#2182]
### Proposal

Clarify positioning and intention of this project.

It's unclear to me, as a brand new user / potential adopter, exactly what Perses is and what problem it aims to solve.

Is it:

- A dashboard specification like CloudEvents where all vendors could standardise (or at least accept) Perses formatted dashboards
- A "full product"? Ie. A dashboarding solution (ie. replacement for a vendor tool such as Grafana)
- Neither
- Both

If it is a specification, where is the spec? I've been trying to find d YAML / JSON document but cannot. I have found [YAML files that look like Kubernetes CRDs](https://perses.dev/docs/perses/v0.47.0/api/dashboard.md/). Are they? How does that work?

**Comment by Nexucis** [comment]
I think it's clearer in the README actually, it's more up to date than what is in the website. 

So to answer your first question, it's both. 

Regarding the next question, as you figured out with the link you shared, yes this is the dashboard specification.
If it's closer to the k8s document, that's on purpose. We wanted to be closer as much as possible from the k8s definitions to then be able easily to provide the dashboard as CRDs.

Hope I have clarified your different questions.
