### ISSUE TITLE
Create and GET project causes 500

### ISSUE THREAD

**Issue by agardnerIT** [perses/perses#2195]
### What did you do?

1. Spin up perses
2. Create a project via ui: `proj1`
3. `http://localhost:8080/api/v1/projects` now gives `{"message":"internal server error"}`

```
ERRO[2024-08-25T14:47:03+10:00] unexpected error not handle                   error="json: error calling MarshalJSON for type json.RawMessage: invalid character 'k' looking for beginning of value"
INFO[2024-08-25T14:47:03+10:00]                                               method=GET status=500 uri=/api/v1/projects
```

### What did you see instead? Under which circumstances?

500 error

### System information

Darwin 23.6.0 arm64

### Perses version

0.47.1

**Comment by Nexucis** [comment]
Could you share the server config please ? 

I just tried with the demo instance and I have no issue creating and getting a project.

**Comment by agardnerIT** [comment]
Sure, I downloaded and extracted the `0.47.1` release and running from that extracted directory:

```
% pwd 
~/Downloads/perses_0.47.1_darwin_arm64

% ls
CHANGELOG.md    README.md       cue             data            percli
LICENSE         config.yaml     cue.mod           perses


% ./perses --config=config.yaml
```

## config.yaml
Built from instructions [here](https://perses.dev/docs/perses/v0.47.0/user-guides/configuration.md/)
```
database:
  file: # the configuration when you want to use the filesystem as a database. Note that you can configure it using the flags, which gives you the choice to not create a configuration file just for that.
    folder: "./data" # It's the path where the file will be read / stored
    extension: "yaml" # The extension of the files read / stored. "yaml" or "json" are the only extension accepted. Yaml is the default one
schemas:
  panels_path: "cue/schemas/panels"
  queries_path: "cue/schemas/queries"
  datasources_path: "cue/schemas/datasources"
  variables_path: "cue/schemas/variables"
```

**Comment by Nexucis** [comment]
This is really a mystery for me.

- I have download the exact same binary/archive (`perses_0.47.1_darwin_arm64`)

- I have the same config

```yaml
database:
  file:
    folder: "./data"
    extension: "json"

schemas:
  panels_path: "./cue/schemas/panels"
  queries_path: "./cue/schemas/queries"
  datasources_path: "./cue/schemas/datasources"
  variables_path: "./cue/schemas/variables"
  interval: "6h"
```

And still I am not able to reproduce the issue you are facing :(

I tried on google chrome and on safari and also with the Perses CLI. All get the correct answer.

```bash
➜  perses_0.47.1_darwin_arm64 ./percli get projects
  NAME  | AGE
--------+------
  proj1 | 5m
```

**Comment by agardnerIT** [comment]
I can reliably repeat this. I copied the binary to a fresh folder, used the default config file and set log level to `debug`:


```
./perses --config config.yaml --log.level debug
```

## config.yaml

Note: folder `./perses` does not exist. Do I need to create it? Or will Perses auto create it on startup?

```
database:
  file:
    folder: "./perses"
    extension: "json"

schemas:
  panels_path: "./cue/schemas/panels"
  queries_path: "./cue/schemas/queries"
  datasources_path: "./cue/schemas/datasources"
  variables_path: "./cue/schemas/variables"
  interval: "6h"

```

## Log Output
```
INFO[2024-09-18T19:47:28+10:00]                                               method=GET status=200 uri=/api/v1/health
ERRO[2024-09-18T19:47:28+10:00] unexpected error while trying to access to the folder "perses/projects"  error="stat perses/projects: not a directory"
ERRO[2024-09-18T19:47:28+10:00] unexpected error not handle                   error="unable to build the query: stat perses/projects: not a directory"
INFO[2024-09-18T19:47:28+10:00]                                               method=GET status=500 uri=/api/v1/projects
INFO[2024-09-18T19:47:28+10:00]                                               method=GET status=200 uri=/api/config
ERRO[2024-09-18T19:47:28+10:00] unexpected error while trying to access to the folder "perses/dashboards"  error="stat perses/dashboards: not a directory"
ERRO[2024-09-18T19:47:28+10:00] unexpected error not handle                   error="unable to build the query: stat perses/dashboards: not a directory"
INFO[2024-09-18T19:47:28+10:00]                                               method=GET status=500 uri="/api/v1/dashboards?metadata_only=true"
INFO[2024-09-18T19:47:28+10:00]                                               method=GET status=200 uri=/8f28e0e1fdb195149f1c.woff2
INFO[2024-09-18T19:47:28+10:00]                                               method=GET status=200 uri=/be36596da218e1eec01c.woff2
INFO[2024-09-18T19:47:36+10:00]                                               method=GET status=200 uri=/dc76fa21c09d3cec2243.woff2
INFO[2024-09-18T19:47:36+10:00]                                               method=GET status=200 uri=/4b21d625362d4f7d84d2.woff2
ERRO[2024-09-18T19:47:39+10:00] unexpected error not handle                   error="mkdir perses: not a directory"
INFO[2024-09-18T19:47:39+10:00]                                               method=POST status=500 uri=/api/v1/projects
```

**Comment by Nexucis** [comment]
ah yeah ok I found what's happening there.

`perses` is the binary and as such it's not possible to have a folder with the same name than the binary. Which cause this issue.

So as workaround, in the config for the key `database.file.folder` instead of having `./perses` you can put something else like `./data`. And that should work

> Note: folder ./perses does not exist. Do I need to create it? Or will Perses auto create it on startup?

Perses is creating what is necessary to make it work so you don't need to do anything.

**Comment by agardnerIT** [comment]
Yup. Got it. Next step. Finding some docs to create a datasource (I'd like to add Dynatrace)

**Comment by Nexucis** [comment]
that's not possible currently since we do not support Dynatrace. So the datasource is not available for them

**Comment by agardnerIT** [comment]
> that's not possible currently since we do not support Dynatrace. So the datasource is not available for them

I wanted to develop and contribute it

**Comment by Nexucis** [comment]
ah sorry I didn't get you wanted to develop it !

So if you are ok with it, I would prefer to wait we finish the new plugin architecture. Because after this, it will be possible to support external plugin.

Like that vendor can develop their datasource into their own organisation and we will reference it
