### ISSUE TITLE
Unexpected vertical scrolling due to echarts native tooltip in timechart

### ISSUE THREAD

**Issue by abelyakin** [perses/perses#2217]
### What did you do?

The timechart component uses custom tooltip but still has config for echart native tooltip. This is causing an unintended side effect where the body element is being vertically stretched, resulting in unnecessary scrolling to an empty area. Deleting this option resolves the issue.

Steps to reproduce on perses demo page.
1. Go to https://demo.perses.dev/projects/perses/dashboards/nodeexporterfull
2. Scroll down and check that page ends where all panels end
3. Trigger tooltip hovering on chart
4. Scroll down and you will get around 800-1000px blank space below panels.

![2024-09-02_20-08](https://github.com/user-attachments/assets/f2722de0-1aaa-4409-828d-7b85e33faf80)

https://github.com/perses/perses/blob/main/ui/components/src/TimeChart/TimeChart.tsx#L229
``` 
tooltip: {
    show: true,
    // ECharts tooltip content hidden by default since we use custom tooltip instead.
    // Stacked bar uses ECharts tooltip so subgroup data shows correctly.
    showContent: isStackedBar,
    trigger: isStackedBar ? 'item' : 'axis',
    appendToBody: true,
}
```

I'd like to understand why this was implemented this way. Can you help me figure out how to fix the scrolling problem without breaking the tooltip's functionality?

### What did you expect to see?

 I expected the tooltip to function without causing any changes to the page's overall layout or scrolling behavior. The tooltip should appear and disappear as needed without affecting the page's vertical dimensions or introducing unnecessary scrollbars.

### What did you see instead? Under which circumstances?

 Instead of the expected behavior, I observed that the body element of the page was being vertically stretched, introducing a scrollbar that allowed scrolling to an empty area below the actual content. This occurs when interacting with the timechart component. The unnecessary vertical space and scrolling persist even after the tooltip is no longer visible.

**Comment by sjcobb** [comment]
Stacked bar chart (visual.display: ‘bar’) still uses the ECharts tooltip, but there is no reason it can’t also use the custom tooltip with a bit of refactoring 

appendToBody is there to avoid getting cutoff from the container that could have ‘overflow: hidden’ (or at one point did, it might not be an issue anymore). Can also try adding the isStackedBar condition to the appendToBody line if that fixes the issue, I do think ‘show: true’ is there intentionally, it might break the axisPointer if it had the isStackedBar condition

**Comment by Nexucis** [comment]
Hello @abelyakin,

This is a bit awkward because you already proposed a fix, but neither @AntoineThebaud or my are able to reproduce the issue.

Could you share what browser you are using ? We tried with firefox and google chrome.

Would you mind to capture your screen to see the bug in a video ? Probably like that we will more understand how you trigger this bug.

**Comment by abelyakin** [comment]
Hello @Nexucis 
I know it can be tricky to reproduce this issue but still it is quite annoying asd

Here is the link to the video: [screen recording](https://github.com/user-attachments/assets/1dbed3d6-d220-4702-ae5c-34b883c20e00)
What I am trying to show here is that initially, everything is fine and the end of the scroll matches the end of the screen (content). However, once I hover over the timeseries chart and trigger the tooltip, the page height increases.

For reference, I am using latest google chrome
