### ISSUE TITLE
Allowing for non tls communication

### ISSUE THREAD

**Issue by Labiote** [perses/perses#2302]
### Proposal

Hello,

Recently, I have been using Perses and had to configure authentication to access my dashboards. So I set up a keycloak server and parametered Perses to have my dashboards not accessible from random people. The configuration has been working fine since I had a session registered and logged in in Keycloak, but Perses keeps saying it can't verify certificates authenticity. Which I guess is because I have self signed certificates from keycloak. I keep having a message saying "Internal error server" instead of the page that is configured after redirection. I assume that Perses can't process authentication without tls enabled ?

So my request is the following :

Could it be possible to add non tls authentication/communication between Perses and other services ? More generally, it would be nice to have the possibility to enable or disable tls directly in the configuration of Perses. Also would be nice to have some configuration to generate self signed certificates when using tls, and/or have the possibility to install our own certificates easily through configuration.

What do you think ? Thanks for your work so far.

**Comment by celian-garcia** [comment]
Hello, can you provide the logs as well? I coded it for the most part and I will check this issue. 
Something I don't understand is how did you get a session if the redirection doesn't work? Do you have a reproduction/keycloak config + perses config that I can try?

**Comment by Labiote** [comment]
Hello, thanks for the feedback first. So I can provide that in more details tomorrow. But from what I remember this is the environment workflow and all :

Environment:
- Everything is running in a kubernetes environment. Perses and keycloak deployed using helm charts.
- Keycloak is running with self signed certificates configuration 
- Perses is configured to have oauth authentication, it has my client secret, client I'd etc
- I have traefik for ingress controller

Issue:
- When I open perses on my browser, it asks me to authenticate using keycloak. I click on it, I have the authentication page of my keycloak server showing, I give my credentials and click on connect. Then a new page shows with just 2 brackets and the message "internal server error". On keycloak admin console I can see that I have an active session on my client. And the logs on perses container show the following : "X.509 Certificate Signed by Unknown Authority", which is an unhandled error apparently

**Comment by celian-garcia** [comment]
Thanks for these details, I will check tomorrow. Last thing is: is it an oauth or oidc config in Perses? I think that keycloak support oidc but this can be also configured with simple oauth. We are using different libraries for each and I will try to address both libraries but this can help me to focus on your specific problem.

**Comment by Labiote** [comment]
Thanks again. So yeah currently I am using it with oauth configuration

**Comment by Nexucis** [comment]
@Labiote the fix is available in the last release (v0.48.0) let us know if it works better for you now

**Comment by Labiote** [comment]
Hello, I testes this this morning and it is working very fine ! I am now able to authenticate behind an insecure keycloak server. Thanks for your work and the response time ! Just a few things though :

The configuration.md (that describes how to configure authentication, tls etc) might have some misleading parameters names. Like, for instance, in the configuration.md file the configuration for tls is described as following :

```Text
# Disable validation of the server certificate.
[ insecure_skip_verify: <boolean> ]
```

But when using this parameter as is in my configuration file, it rises an error. In fact, in the perses code, the parameter is described as :

```Go
	InsecureSkipVerify bool   `yaml:"insecureSkipVerify" json:"insecureSkipVerify"`
```

So, to actually configure this you need to specify the parameter as "insecureSkipVerify". It's just minor detail, I figured it out rapidly, but maybe the configuration.md should be updated to have the correct parameters name ?

Maybe I can create an other ticket for that if it is out of the scope of this issue.

Otherwise, thanks again !

**Comment by Nexucis** [comment]
@Labiote ah yes nice catch thanks ! Yeah the documentation should be totally updated to reflect the correct key to be used.
Would you like to fix it :) ?

**Comment by Labiote** [comment]
Would be my pleasure ! ^^
