### ISSUE TITLE
Panic with percli offline migrate

### ISSUE THREAD

**Issue by sunng87** [perses/perses#2345]
### What did you do?

I'm trying to migrate the grafana NodeExporterFull dashboard to Perses using percli.

### What did you see instead? Under which circumstances?

I'm getting this panic error

```
./bin/percli migrate -f ~/tmp/node-exporter-full.json 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc3129b]

goroutine 1 [running]:
github.com/perses/perses/internal/cli/cmd/migrate.(*option).offlineExecution(0xc00032e8f0, {0xc000706000?, 0xcf2d80?, 0xc000300150?})
        /home/nsun/workspace/perses/internal/cli/cmd/migrate/migrate.go:132 +0x5b
github.com/perses/perses/internal/cli/cmd/migrate.(*option).Execute(0xc00032e8f0)
        /home/nsun/workspace/perses/internal/cli/cmd/migrate/migrate.go:115 +0x10a
github.com/perses/perses/internal/cli/cmd.Run({0xf5d4a0, 0xc00032e8f0}, 0xc000334608, {0xc000308440, 0x0, 0x2})
        /home/nsun/workspace/perses/internal/cli/cmd/cmd.go:42 +0xdd
github.com/perses/perses/internal/cli/cmd/migrate.NewCMD.func1(0xc00032d300?, {0xc000308440?, 0x4?, 0xdd8ed7?})
        /home/nsun/workspace/perses/internal/cli/cmd/migrate/migrate.go:153 +0x32
github.com/spf13/cobra.(*Command).execute(0xc000334608, {0xc000308420, 0x2, 0x2})
        /home/nsun/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000328008)
        /home/nsun/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/nsun/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
        /home/nsun/workspace/perses/cmd/percli/main.go:97 +0x105

```

The json file is downloaded from Grafana website:
[1860_rev37.json](https://github.com/user-attachments/files/17385175/1860_rev37.json)

By the way, the online import feature works correctly.

### Perses version

Master branch

**Comment by celian-garcia** [comment]
Interesting that you see this message only in "offline" I think the migration cannot be done offline as long as it needs the API endpoint. @AntoineThebaud you can confirm ? 

There should be a far better error message though, and not a pity nil dereference 😅. Let me set a big priority on this.

**Comment by celian-garcia** [comment]
Oops I see the code failing is named ``offlineExecution`` so I might be completely wrong in my assumption 😅

**Comment by AntoineThebaud** [comment]
Yes there is a logic to use the local fs instead of a remote Perses server in order to retrieve the schemas powering the migration.
Will have to dig in the issue here..
