### ISSUE TITLE
Perses not usable with Grafana Mimir

### ISSUE THREAD

**Issue by rasmusvan** [perses/perses#2420]
### What did you do?

Tried using Perses having Grafana Mimir as datasource

### What did you expect to see?

I expected to see Perses work the same way as it does with Prometheus

### What did you see instead? Under which circumstances?

404 Not Found error which is caused by Perses using parse_query. Prometheus official documentation states: "This endpoint is experimental and might change in the future. **It is currently only meant to be used by Prometheus' own web UI**, and the endpoint name and exact format returned may change from one Prometheus version to another. It may also be removed again in case it is no longer needed by the UI."

https://prometheus.io/docs/prometheus/latest/querying/api/#parsing-a-promql-expressions-into-a-abstract-syntax-tree-ast

### System information

Darwin 23.5.0 arm64

### Perses version

0.49.0

**Comment by AntoineThebaud** [comment]
It works... the error is related to the new Tree view feature, and it could be indeed improve to stop firing queries / raising errors in console when the datasource is not compatible, however this doesnt prevent the promQL query to be send to the datasource to display actual results. Closing as invalid.
