### ISSUE TITLE
Unable to Pre-Assign Roles to Oauth-Authenticated Users  

### ISSUE THREAD

**Issue by kamijin-fanta** [perses/perses#2428]
### Proposal

Currently, in Perses, it is not possible to pre-assign roles to users that will be created in the future via Oauth authentication. This limitation arises from the following behaviors:

### Users that do not yet exist cannot be included in RoleBinding.

When attempting to create a `RoleBinding` with `percli apply` that includes a user (e.g., `alice`) who does not yet exist, Perses returns an error.  

```json  
{  
  "kind": "GlobalRoleBinding",  
  "metadata": {  
    "name": "admin"  
  },  
  "spec": {  
    "role": "admin",  
    "subjects": [  
      {  
        "kind": "User",  
        "name": "alice"  
      }  
    ]  
  }  
}
```  

```
bad request: user subject name "alice" doesn't exist StatusCode: 400
```  

### Oauth users cannot be created in advance.

When attempting to create a user like the following, Perses also returns an error.  

```json  
{  
  "kind": "User",  
  "metadata": {  
    "name": "alice"  
  },  
  "spec": {  
    "oauthProviders": [  
      {  
        "issuer": "http://localhost/openid",  
        "email": "alice@example.com",  
        "subject": "123456789"  
      }  
    ]  
  }  
}  
```  

```
bad request: password cannot be empty StatusCode: 400
```  

### Users with both `nativeProvider` and `oauthProviders` can be created.

Users specifying both `nativeProvider` and `oauthProviders` appear to be created successfully:  

```json  
{  
  "kind": "User",  
  "metadata": {  
    "name": "alice"  
  },  
  "spec": {  
    "nativeProvider": {  
        "password": "password"  
    },  
    "oauthProviders": [  
      {  
        "issuer": "http://localhost/openid",  
        "email": "alice@example.com",  
        "subject": "123456789"  
      }  
    ]  
  }  
}  
```  

### However, Oauth login fails for users with both `nativeProvider` and `oauthProviders`.

Attempting to log in via Oauth for such users results in an Internal Server Error in the browser, and the following log is recorded in the console:  

```
level=error msg="Failed to sync user in database." error="this user is already registered with the native provider"
```  

## Suggestions for Improvement  

- Allow users to be created without specifying a password.  
- Enable Oauth login for users with `nativeProvider` credentials.  

Thank you for developing this fantastic product. Please let me know if additional information is required, or I can assist by opening a pull request.

**Comment by celian-garcia** [comment]
Hello, let me answer you point by point 
Users that do not yet exist cannot be included in RoleBinding.
=> yes, I think we should do something about that. As this is your primarily issue. We'll ease the rolebinding creation/update to allow not existing users. To be followed here https://github.com/perses/perses/issues/2270
 
Oauth users cannot be created in advance.
=> This is wanted. We don't really want to trust users for creating oauth users properly. The fields can be quite complex and undocumented.
 
Users with both nativeProvider and oauthProviders can be created.
=> This is a bug. I just created an issue about that https://github.com/perses/perses/issues/2429
 
However, Oauth login fails for users with both nativeProvider and oauthProviders.
=> Again on purpose, details on the issue created right above.

**Comment by celian-garcia** [comment]
Closing the issue has to be reported in the two other issues mentioned. 
Thanks @kamijin-fanta for sharing your experience!

**Comment by kamijin-fanta** [comment]
Thank you for the incredibly quick resolution! This will make Perses much more user-friendly!
