### ISSUE TITLE
Enforce return type on functions and modules

### ISSUE THREAD

**Issue by Gladorme** [perses/perses#2444]
### Proposal

Today we are currently not enforcing return types on functions + modules. However, it can make it harder for user to guess which struct to use when using perses components as embedded. Plus, slowing down TS compiler / linter and it's easing code review. More info about slow types: [https://jsr.io/docs/about-slow-types](https://jsr.io/docs/about-slow-types)

**Comment by Gladorme** [comment]
Disabled by rules: [https://github.com/perses/perses/blob/main/ui/.eslintrc.base.js#L56](https://github.com/perses/perses/blob/main/ui/.eslintrc.base.js#L56)

**Comment by Nexucis** [comment]
yes definitely yes

**Comment by celian-garcia** [comment]
Yes yes yes. Good luck to the implementer 😄

**Comment by Gladorme** [comment]
It can be made package by package, but yeah it will not be fast 😅
