### ISSUE TITLE
Ephemeral dashboard prefix added to dashboard list

### ISSUE THREAD

**Issue by Syldinn** [perses/perses#2457]
### Proposal

Hello,

I have been trying out ephemeral dashboards in a Jenkins CI environment.

The `--prefix` flag is really handy to avoid collisions between pull requests done on a given dashboard, however it results in 2 seemingly identical dashboards in the UI, because the display name is not altered.
They can only be distinguished based on the URL (or going through specific pieces of the UI that display the dashboard ID, like the deletion prompt).

It would be nice to have the prefix added somewhere (as a "tag", as a prefix in the dashboard's display name...) to identify easily the various ephemeral dashboards.

**Comment by AntoineThebaud** [comment]
Adding the prefix to the display name too is the right thing to do I guess. The day we support [dashboard tags](https://github.com/perses/perses/issues/1733) this would indeed be interesting to put the information there as well.
