### ISSUE TITLE
``ng test`` is not run by the CI pipeline 

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#28]
It seems that the ``ng test`` command is not run by Circle CI. The goal here is to activate and to fix the tests because they are likely to be red

**Comment by celian-garcia** [comment]
Absolutely ! Let me create a different issue :)

**Comment by Nexucis** [comment]
I think we can close this issue as the move to React is on going. This issue won't be accurate anymore

**Comment by celian-garcia** [comment]
I don't think that move to react will prevent us to make and run unit tests or neither modify magically our pipeline. Even in react there is the need to have some unit tests runned in the CI.

**Comment by Nexucis** [comment]
Yup but that would be another way and probably another issue if we missed it
