### ISSUE TITLE
Front should be formatted by eslint

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#29]
As discussed in #28, the official typescript linter is eslint and should be used in place of ``ng lint``

**Comment by Nexucis** [comment]
Could be an idea to have the linter of the front-end as a Github action like it is for the backend. It would be consistent at least

**Comment by Nexucis** [comment]
job to run the front-end linter has been moved to a github action thanks to #35

**Comment by celian-garcia** [comment]
Sounds verbose for a GitHub action, isn't there an npm GitHub action that can do 
Use npm 
Do install, lint 
Basta
I'm gonna check when integrating eslint

**Comment by Nexucis** [comment]
Yeah you can find something like that. But that's not really an official gh actions. So I prefere like that. Could be a possibility one day to create out own gh action if we think it becomes painful
