### ISSUE TITLE
Build failing  Conflicting peer dependency: react@18.0.0

### ISSUE THREAD

**Issue by KrisBuytaert** [perses/perses#423]
After having upgraded both npm and node I`m still struggling to get a working build 

Do I need different versions or what am I doing wrong ? 

[sdog@perses.o11ylab.o11y.eu perses]$ npm --version 
8.5.0
[sdog@perses.o11ylab.o11y.eu perses]$ node --version 
v16.14.2
[sdog@perses.o11ylab.o11y.eu perses]$ make 
rm -rf ./bin
./scripts/ui_release.sh --clean
cd ./ui && npm run clean

> perses-dev@0.1.0 clean
> rimraf .build-cache && npm run clean --workspaces

> @perses-dev/app@0.3.1 clean
> rimraf dist/

> @perses-dev/components@0.3.1 clean
> rimraf dist/

> @perses-dev/core@0.3.1 clean
> rimraf dist/

> @perses-dev/dashboards@0.3.1 clean
> rimraf dist/

> @perses-dev/panels-plugin@0.3.1 clean
> rimraf dist/

> @perses-dev/plugin-system@0.3.1 clean
> rimraf dist/

> @perses-dev/prometheus-plugin@0.3.1 clean
> rimraf dist/

cd ./ui && npm install && npm run build
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @testing-library/react@13.1.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.9.0
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.8.2" from @perses-dev/app@0.3.1
npm ERR!     app
npm ERR!       @perses-dev/app@0.3.1
npm ERR!       node_modules/@perses-dev/app
npm ERR!         workspace app from the root project
npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.8.1
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^11.8.1" from @perses-dev/app@0.3.1
npm ERR!       app
npm ERR!         @perses-dev/app@0.3.1
npm ERR!         node_modules/@perses-dev/app
npm ERR!       4 more (@mui/material, notistack, @mui/system, @mui/styled-engine)
npm ERR!     4 more (@mui/material, notistack, @mui/system, @mui/styled-engine)
npm ERR!   react@"^17.0.2" from @perses-dev/app@0.3.1
npm ERR!   app
npm ERR!     @perses-dev/app@0.3.1
npm ERR!     node_modules/@perses-dev/app
npm ERR!       workspace app from the root project
npm ERR!   22 more (@perses-dev/components, @perses-dev/core, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from @testing-library/react@13.1.1
npm ERR! node_modules/@testing-library/react
npm ERR!   dev @testing-library/react@"^13.1.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.0.0" from @testing-library/react@13.1.1
npm ERR!   node_modules/@testing-library/react
npm ERR!     dev @testing-library/react@"^13.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/sdog/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sdog/.npm/_logs/2022-04-25T08_59_28_977Z-debug-0.log
make: *** [Makefile:79: build-ui] Error 1

**Comment by KrisBuytaert** [comment]
npm install --legacy-peer-deps

fixed it

**Comment by Nexucis** [comment]
your issue looks weird actually. In perses we are not using react v18, so this error shouldn't exit
