### ISSUE TITLE
Perses Governance

### ISSUE THREAD

**Issue by geekygirldawn** [perses/perses#429]
I'm planning on proposing a super simple governance model for Perses with existing maintainers selecting / approving new maintainers.  Before I start, can I get a list of the existing maintainers? Knowing how many maintainers we have now and who they are will help me make a proposal that will work for us today with the idea that we can grow it over time as needed.

**Comment by Nexucis** [comment]
Hi @geekygirldawn !

Oh interesting, thank you for doing it !

>  Knowing how many maintainers we have now and who they are 

When you say that, are you asking what do they do in Perses, or are you thinking about something else ?

Here the current list of persons that actively contribute to Perses in term of code:

- Antoine Thebaud (@AntoineThebaud)
- Augustin Husson (@Nexucis)
- Luke Tillman (@LukeTillman)
- Steven Cobb (@sjcobb)

Then you have : 

- Julius Volz (@juliusv)
- Rob Skillington (@robskillington)
- Karan Malhi

that are helping by giving ideas, defining in an understable way the scope of Perses, talking about it around them ...etc.

Does it help ?

**Comment by geekygirldawn** [comment]
I was thinking about including 2 roles:
1) Contributors: People who contribute in various ways (including ideas), but who don't have edit rights to merge PRs.
2) Maintainers: People who can merge contributions from other people.

**Comment by Nexucis** [comment]
yes all 4 contributeurs are owner of the perses org and so can merge the PRs.

Even the 3 others can also merge it, but it's unlikely that will happen ( But hey, it can change and then I will say something wrong haha)

**Comment by Nexucis** [comment]
and the last person that can merge PRs today is Charles Ma (@chucknthem), but I don't know his status.

**Comment by geekygirldawn** [comment]
It might be a good idea to scrub the list of org owners and remove access for people who aren't actively contributing.

I also see a few more contributors here: https://github.com/perses/perses/graphs/contributors if they are still active.

I also wonder if we should use a settings.yaml file to provide more transparency around who has access to do what? Chris set that up for CoreDash, but it's not something we need to do right away.
https://github.com/coredashio/community/blob/main/.github/settings.yml 

I think I have what I need right now. I will look in more detail about where people have actually made contributions, and make a proposal in a PR for who the maintainers *should* be based on contributions. Once I have a proposal, if I get anything wrong, I'm sure people will tell me 🤣

**Comment by Nexucis** [comment]
> I also see a few more contributors here: https://github.com/perses/perses/graphs/contributors if they are still active.

Na the only contributors that are active are the 4th one above.

> I think I have what I need right now. I will look in more detail about where people have actually made contributions, and make a proposal in a PR for who the maintainers should be based on contributions. Once I have a proposal, if I get anything wrong, I'm sure people will tell me

cool :). Don't hesitate to ping me if you need further details

**Comment by roidelapluie** [comment]
> I also wonder if we should use a settings.yaml file to provide more transparency around who has access to do what? Chris set that up for CoreDash, but it's not something we need to do right away.

While considering this for Prometheus, it seemed to risky to introduce this. While it brings welcomed transparency, it turns every contributor into an admin.

**Comment by Nexucis** [comment]
I think we can close this issue right @geekygirldawn  ?

**Comment by geekygirldawn** [comment]
Yes, I'll close this. Thanks for all of your help (and patience) with this! :)
