### ISSUE TITLE
Convert react grid layout css files to using MUI Global Styles

### ISSUE THREAD

**Issue by eunicorn** [perses/perses#511]
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';

Currently we need to import these two css files in order for react-grid-layout to work. This means that users consuming the dashboard library will also need to import these files in order for dashboard to work.

It's best if we can pass the rgl css to MUI global styles https://mui.com/material-ui/api/global-styles/ so users don't have to worry about any external css files.

**Comment by Nexucis** [comment]
isn't already fixed with #510 @eunicorn ?

**Comment by eunicorn** [comment]
it's fixed with https://github.com/perses/perses/pull/524
