### ISSUE TITLE
Allow set of a color when you have only one timeseries for query

### ISSUE THREAD

**Issue by Nexucis** [perses/perses#557]
In the `LineChart`, some of our users would like to be able to set a color only if the query you can configure returned a single timeseries.

In case there is more than one, then the color set in the query is ignored by the panel.

**Comment by sjcobb** [comment]
I’ve been thinking about this more as I’m reading comments on #1031 

It might actually be pretty easy to do, the spec for `palette` could potentially be:

```
kind: ‘Single’
color: string 
fallback?: ‘Auto’ | ‘Categorical’ // palette kinds 
```

Or maybe a ‘mode’ instead and then ‘fallback_palette’ 🤔 

Regardless, we could make it default to what is proposed in this Issue, but give optional properties to customize fallback behavior further

**Comment by sjcobb** [comment]
Thinking of changing our default back to ‘auto’ so we have consistent colors for same series names across panels again and adding `visual.palette.singleValueColor` as an optional property.  Then add a color picker control where the color selected kicks in when one series returned, when more than one, just use visual.palette.mode as fallback
