### ISSUE TITLE
Couple variables issues

### ISSUE THREAD

**Issue by Nexucis** [perses/perses#645]
1. I was playing a bit the variable and I noticed for the variable `job` if you move from `node` to `all` then back to `node`, the variable `instance` doesn't have anymore the value `demo.do.prometheus.io:9200`.

Maybe an issue when running the query for the variable ?

https://user-images.githubusercontent.com/4548045/195874873-b8ef47c5-14c7-4681-b942-57553182a41c.mov

2. When we select multiple values/lines, it's not super clear at the first glance it select multiple things. Specially with the light theme.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/4548045/195875846-37a6be92-8fe0-4589-b4b8-1bd051e39021.png">

<img width="228" alt="image" src="https://user-images.githubusercontent.com/4548045/195875989-dc1c93ed-49d9-4151-ad25-6c22a027c5c7.png">

FYI @saminzadeh :). Since the implementation of the variables is still on going, perhaps you already noticed what I described above, or it's normal it's like that. Let me know if the issue is useful :)

**Comment by saminzadeh** [comment]
Ah, thats due to a bad dashboard variable definition. When "All" is selected for `job`, the value resolves to regex `(val1|val2)` which is not compatible with the `instance` variable definition. 

We need to update the demo dashboard variable definition to disable Multiple values for `job` or change `instance` to accept regex:

eg. `'up{job="$job"}'` should be `'up{job=~"$job"}'`

https://github.com/perses/perses/blob/main/ui/app/sample-data/demoDashboard.ts#L53

> When we select multiple values/lines, it's not super clear at the first glance it select multiple things. Specially with the light theme.

Yeah agreed, it's a bit hard to tell with the default MUI inputs. Let's plan on updating that soon

**Comment by Nexucis** [comment]
ah ok. But isn't weird when you pass from `All` value to `node` for the `job` variable, the `instance` variable doesn't have the value `demo.do.prometheus.io:9200` anymore ? 

Besides when you start the demo, the variable `instance` has this value in the dropdown. I'm more questioning the switch from the value `all` to `node` that seems buggy. 

I hope it's clearer saying like that :)

> Yeah agreed, it's a bit hard to tell with the default MUI inputs. Let's plan on updating that soon

cool :)

**Comment by saminzadeh** [comment]
> ah ok. But isn't weird when you pass from `All` value to `node` for the `job` variable, the `instance` variable doesn't have the value `demo.do.prometheus.io:9200` anymore ?
> 
> Besides when you start the demo, the variable `instance` has this value in the dropdown. I'm more questioning the switch from the value `all` to `node` that seems buggy.
> 
> I hope it's clearer saying like that :)
> 
> > Yeah agreed, it's a bit hard to tell with the default MUI inputs. Let's plan on updating that soon
> 
> cool :)

Ah yeah, I see the issue. It's because we set a default value `node` for the `job` variable in the Dashboard definition. But since "All" is enabled, when you switch back to Node it will be `(node)` and the query will be: `up{job="(node)"}` which doesn't return anything
