### ISSUE TITLE
Browser freeze when editing panel `Legend Example` in dashboard `Benchmark`

### ISSUE THREAD

**Issue by Nexucis** [perses/perses#819]
## Steps to reproduce 
1. Go on the `Benchmark` dashboard
2. Click on the `edit` button to activate the edit mode
3. Click on the `edit` button of the panel `Legend Example`

## Result

After a few seconds, the page is frozen and you can just kill the browser tab. I didn't notice an error in the console when it's happening.

**Comment by cndonovan** [comment]
@Nexucis Would you like to confirm that this has been fixed and close this issue if it is?
