### ISSUE TITLE
Add functionality to assist with generating changelog

### ISSUE THREAD

**Issue by juliepagano** [perses/perses#838]
Creating this based on a discussion in the meeting this morning. The current process for manually updating the changelog creates a bit of toil around things like merge conflicts and forgetting to update the changelog for PRs. It would be helpful to have some tooling to assist with generating the changelog when creating a release based on commits and pull requests. 

Below is a summary of my understanding of the problem and some notes from our discussions.

## Script to autogenerate changelog

**Output:**
- A script that a maintainer can run when creating a release to assist with generating the changelog.

**Notes from discussion:**
- We should not rely solely on the autogenerated changelog. It should generate a rough draft that is then reviewed and adjusted (as needed) by the person making the release.
- We likely need to improve our approach to PRs and merging to `main` to make it more feasible to generate the changelog. See next section for notes on this.
- It would be helpful if there was a prefix people can put on commits that tells the changelog to skip them. 
- We do not care about keeping an "unreleased" section of our changelog. It exists now to help generate the changelog, but can go away when we add the script.

**Ideas:**
- Looking at some popular open source projects, many of them have written their own scripts for this, usually with it focused on parsing git commits. We *might* be able to leverage an open source tool, but many of them are really focused on detailed commit semantics or aren't aligned with our approach. `auto-changelog` might work, but looks like it would need a lot of customization -- it might be easier just to write our own script.
- If we require people start using the prefixes we want (`[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`, `[BREAKINGCHANGE]`) in the changelog in commit titles, that would make it relatively easy to parse commits.
- Could suggest a prefix like `[NOCHANGELOG]` or `[IGNORE]` or something like that for the case where we know a commit doesn't need to be in the changelog.

## Improvements to commits merged to `main`

For automation to be helpful, the commits that make it to `main` should ideally be organized and named in a way that aligns with the changelog. This would also be helpful for anyone working in the repo looking through the [commits]( https://github.com/perses/perses/commits/main) and trying to make sense of them. 

**Output:**
- Guidelines about title naming conventions and how they translate to the changelog.
- Guidelines about merging PRs to `main`.

**Notes from discussion:**
- We should not require a full squash and merge because sometimes a pull request contains multiple entries for a changelog. 
- On the flip side, we should not merge ALL THE COMMITS in a PR, which can include a lot of noise (things like "responded to PR feedback", "fixed linter error"). 

**Ideas:**
- When a PR is a single unit of work, squash and merge to a single commit with a meaningful title and message following a naming convention.
- When a PR is multiple units of work, do one of the following:
   - Rebase the commit down to N commits with meaningful titles and messages. *This could be difficult to do with complex PRs, but would be easier for auto-generating a changelog because you only have to look at commit titles.*
   - Squash and merge to a single commit with a meaningful title AND a body with a list containing N entries with meaningful titles for the changes. *This would require whatever tooling we use to generate the changelog to be able to parse this information out of the commit body.*
 - It would be helpful if we could programmatically encourage this, but that's complicated because it happens at merge. When you squash and merge, it defaults to using the PR title, so we could add a github action that does some basic checking on the PR title and gives you feedback about it.

**Comment by juliepagano** [comment]
Assigning to @Nexucis since he mentioned he would look into this in our discussion this morning.

**Comment by LukeTillman** [comment]
> For the moment, I'm starting by supposing it will be at the beginning. We can improve afterwards.

Yeah, really I would want support for the end. We were talking in Slack and having a long prefix like `[ENHANCEMENT]` before PR titles just makes them harder to understand at first glance and sometimes ends up with the "real info" in the title getting cut off in things like the PR list view.

**Comment by juliepagano** [comment]
I don't have strong feelings about where the "tags" like `[ENHANCEMENT]` go, but I think it would be a good idea to standardize wherever they go (beginning or end of title) for consistency in looking at the commit log, pull requests, etc., where we won't be able to automagically shift it to a consistent location like we could for the changelog.

**Comment by sjcobb** [comment]
To Luke's point about commit messages being different when a PR only has one commit, maybe we could play around with some of these settings: https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

**Comment by Nexucis** [comment]
The last thing to do to close this issue is to create a PR template and we should be good.

@LukeTillman FYI the prefix can be put anywhere in the commit message / PR title and it's not case sensitive.

**Comment by juliepagano** [comment]
Closing now that the PR template is created.
