### ISSUE TITLE
label_replace() replacement argument is wrongly rejected as unknown variable

### ISSUE THREAD

**Issue by AntoineThebaud** [perses/perses#859]
See [label_replace()](https://prometheus.io/docs/prometheus/latest/querying/functions/#label_replace) documentation. The `replacement` argument can use capturing groups like `$1`, `$2` that get wrongly interpreted as dashboard variables by the backend validation, which makes it fail.

```json
{
    "message": "bad request: variable \"1\" is used in the variable \"extlabels_prometheus\" but not defined"
}
```

**Comment by Nexucis** [comment]
after discussing with Antoine, a way to mitigate the issue is to forbid the possibility to name a variable with just a number.
