### ISSUE TITLE
Demo Environment

### ISSUE THREAD

**Issue by tenmozes** [perses/perses#883]
Hey folks, this is a fantastic project.
If you have any plans to add a Demo environment or ship a Docker container with the demo that significantly simplify the adoption

**Comment by Nexucis** [comment]
hey @tenmozes, thank you !

Well, we want to do it for sure, but when, that's another question :).
We are providing docker image already, perhaps we just need to write a `getting started`. Maybe it can be a start to help the adoption

**Comment by sjcobb** [comment]
I’d really love to have a play.perses.dev site that always runs the latest build someday once things are more stable

**Comment by Nexucis** [comment]
it's in work in progress, but we have a beginning of a demo here: https://demo.perses.dev/ :)

**Comment by Nexucis** [comment]
Perses demo is setup, we can for sure improve by creating local prometheus and node exporter, but it can be done later.
