### ISSUE TITLE
Set up markdown formatter for consistency

### ISSUE THREAD

**Issue by juliepagano** [perses/perses#889]
We've had a few PRs where different folks have different default formatters from their text editors auto-changing markdown, which leads to messy diffs. We should set up a consistent tool for this to avoid the noise, ideally one that easily integrates into the text editors being used by most maintainers.

I think the UI devs are mostly using vscode, and we use prettier for formatting our UI code, so that might be a good option, but I'm not sure how well that would work for our backend collaborators who are using intellij. Will need to investigate.

**Comment by Nexucis** [comment]
we could use [mdox](https://github.com/bwplotka/mdox). I tried it and it looks ok.
The only thing I dislike is that it inline every paragraph. I would prefer to set a maximum number of character per line. That would be nice.

**Comment by Nexucis** [comment]
I have created an issue on the repo to tackle that: https://github.com/bwplotka/mdox/issues/100. 
Maybe they will like the idea as well.
