### ISSUE TITLE
Support ARM Chip arcitecture in docker image

### ISSUE THREAD

**Issue by AlonMiz** [perses/perses#957]
Hi, looks like a great project! 👏 

I tried to run the docker on my m1 apple chip.
```
Unable to find image 'persesdev/perses:latest' locally
latest: Pulling from persesdev/perses
fc251a6e7981: Pull complete
99acb004d957: Pull complete
3c747f87a046: Pull complete
da755c413810: Pull complete
828cb559575c: Pull complete
b2ec7374fe6b: Pull complete
b7d2660d815c: Pull complete
fdbbd84be376: Pull complete
Digest: sha256:f160ee15b11f4855259bc7b230be117b113e251fb427d3d24c8ac0b41e34dadb
Status: Downloaded newer image for persesdev/perses:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
1ac6454dbcb3ee04fe3f5636210b580aa8bc8055712b984a0a1d30009b2d9a0d
```

supporting multi-platform docker is possible via
https://docs.docker.com/build/building/multi-platform/
🙏

**Comment by Nexucis** [comment]
Hello,

It might be interesting to do it yeah. The only thing that bothering me is more the way the docker build is managed by goreleaser. It would be sad to duplicate the docker build config for each platform user would like to see supported.

**Comment by Romain-Geissler-1A** [comment]
Hi,

I don't know if you are aware, but we use perses in my company. Our company is currently migrating to ARM as well, so we would also find this interesting to have ;) Maybe @Nexucis we can find an agreement with my employer to pay you to implement this :D

Cheers,
Romain

**Comment by Nexucis** [comment]
hopefully running perses on arm (with docker or using the binary) will be available on the next release (v0.30.0) :)

**Comment by capttrousers** [comment]
I just tried pulling v30, I see arm64 listed in the docker hub tags list, but I get this error:
```
docker pull persesdev/perses:latest
latest: Pulling from persesdev/perses
no matching manifest for linux/arm/v8 in the manifest list entries
```

Is there a way to get the arm64 image? I'm trying this on a raspberrypi 4, with `uname -m` output: `aarch64`

**Comment by Romain-Geissler-1A** [comment]
Hi,

We have some aarch64 servers where @Nexucis and I work, and for me it seems to work (I have a connection named `aarch64` which targets the arm machine:

```
rgeissler@ncerndobedev6097:~> podman -c aarch64 run --rm --pull=always docker.io/persesdev/perses                                                                                                                   5:37PM
Trying to pull docker.io/persesdev/perses:latest...
Getting image source signatures
Copying blob sha256:d3c894b5b2b0fa857549aeb6cbc38b038b5b2828736be37b6d9fff0b886f12fd
Copying blob sha256:af5e259bb08162360bd1c9cb59d387801e136f7e4582b3e65655f5293f66b3d5
Copying blob sha256:b4ca4c215f483111b64ec6919f1659ff475d7080a649d6acd78a6ade562a4a63
Copying blob sha256:960043b8858c3c30f1d79dcc49adb2804fd35c2510729e67685b298b2ca746b7
Copying blob sha256:02cd68c0cbf64abe9738767877756b33f50fff5d88583fdc74b66beffa77694b
Copying blob sha256:eebb06941f3e57b2e40a0e9cbd798dacef9b04d89ebaa8896be5f17c976f8666
Copying blob sha256:b40161cd83fc5d470d6abe50e87aa288481b6b89137012881d74187cfbf9f502
Copying blob sha256:46ba3f23f1d3fb1440deeb279716e4377e79e61736ec2227270349b9618a0fdd
Copying blob sha256:4fa131a1b726b2d6468d461e7d8867a2157d5671f712461d8abd126155fdf9ce
Copying blob sha256:4e6fc8606bb1c2caf402854fdd659b1fd88c97605d82eedea1dcd259db38ce5e
Copying blob sha256:0fcad6d918a6c92bf8cc0ba5edbe98cf240da9bf6de9fbfba0b94276d5025e6e
Copying blob sha256:5d67843da8a0a75a5e1b35b0c965701c045842e835e9f6daabcfc510ced25344
Copying blob sha256:d82dedb32fbc9b8b4d4bbfd26cb48ba71cbddd21dc1510ede3fa51a4366dfa52
Copying blob sha256:781d713ee75f96069d846bbea005172b16530dcb2e38c59563515cc93d36590e
Copying blob sha256:b8858b1fe49f005619a05e0acff538f1de467a09887c86dc55b8f75921e21cbd
Copying blob sha256:6cd070a4d3bd74136772f5caab277e88fff7f5ea45541a1f2a4f41c79892ef47
Copying blob sha256:83af12b5328999be3bef991197f2975b0656f6ba36d1441a29629a2a1ce3a93e
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying config sha256:221a11b7f5065105ea6a2b16d4380e302b1a301f2a45697cad87ad12ac89f453
Writing manifest to image destination
Storing signatures


______
| ___ \
| |_/ /__ _ __ ___  ___  ___
|  __/ _ \ '__/ __|/ _ \/ __|
| | |  __/ |  \__ \  __/\__ \
\_|  \___|_|  |___/\___||___/  0.30.0

All your monitoring dashboards in one place.               <\
                                                            \\
--------------==========================================>|||<*>//////]
                                                            //
                                                           </
⇨ http server started on [::]:8080 
```

And I doubled checked directly on the machine that this running container used an ELF aarch64 binary:

```
rgeissler@ncearmdev002:~> ps aux | grep perses   
1114109  3715553  142  0.0 741824 21248 ?        Ssl  17:41   0:05 /bin/perses --config=/etc/perses/config.yaml --log.level=error
rgeissl+ 3715651  0.0  0.0 216640  1664 pts/0    S+   17:41   0:00 grep --color=auto perses
rgeissler@ncearmdev002:~> podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED        STATUS            PORTS       NAMES
7b87b73fe374  docker.io/persesdev/perses:latest  --config=/etc/per...  8 seconds ago  Up 8 seconds ago              gallant_mahavira
rgeissler@ncearmdev002:~> podman unshare podman mount 7b87b73fe374     
/remote/users/rgeissler/.local/share/containers/storage/overlay/9d288fc59da0bc9c9faee70ecc5bb389effa15ac4b31382527f3015f06a3a744/merged
rgeissler@ncearmdev002:~> podman unshare file /remote/users/rgeissler/.local/share/containers/storage/overlay/9d288fc59da0bc9c9faee70ecc5bb389effa15ac4b31382527f3015f06a3a744/merged/bin/perses
/remote/users/rgeissler/.local/share/containers/storage/overlay/9d288fc59da0bc9c9faee70ecc5bb389effa15ac4b31382527f3015f06a3a744/merged/bin/perses: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
```

So the only thing I can say is that it works for us.

Cheers,
Romain

**Comment by Romain-Geissler-1A** [comment]
Actually your docker config seems weird. I don't know anything like `arm/v8`, it should be `arm64` (which assums by default the `v8` CPU variant. I would strongly advise you to upgrade your docker daemon/client as I think it might be outdated. On our side we use Docker 23 and podman 4.2, but my past experiment with multi-arch image on aarch64 also worked fine with Docker 20.10.

**Comment by capttrousers** [comment]
Thanks for the quick responses. I'm just using plain docker, no podman.
Here's the version number
```
docker --version
Docker version 23.0.4, build f480fb1
```
Happy to provide more sysinfo as well. I tried running it with the exact sha of the arm64 image:
```
docker run \
	--name perses \
	-d \
	-p 127.0.0.1:8080:8080 \
	--platform aarch64 \
        persesdev/perses:latest@sha256:f500191929c4b1f180affea31837e682714b2632623eeaa80dedd5b4b7025efe
```
And also tried `--platform arm64` but it starts the container, exits 3 seconds in with `159` and docker logs <container id> shows nothing

**Comment by capttrousers** [comment]
Ok update, looks like my raspberrypi is indeed 64bit arm, however I originally installed raspbian buster which I guess only supported 32bit. I upgraded to bullseye, but for some reason dpkg still thinks it's 32 bit ( I think)

This post sheds a bit more light: https://forums.docker.com/t/docker-on-raspbian-64-bit-with-arm64v8-image/99110

So this must be something with my machine's OS. I'll keep digging and try getting this working

**Comment by Romain-Geissler-1A** [comment]
From docker (and podman) point of view, `--platform=aarch64` and `--platform=arm64` are synonyms, internally the normalization logic will rewrite all this to `linux/arm64` which is the officially specified OCI platform format, found in OCI manifests.

I advise you to double check your OS/kernel really is an aarch64 one and not some 32 bits armv7 one (so with `uname -a`). Also I advise you for your testing to remove all the things which are using unique resources (so the `--name perses` and `-p 127.0.0.1:8080:8080` flags, and to remove the `-d` flag so you can see easily the output.

Also note that an exit code 159 seems to hint at a signal 31 (159 - 128 = 31), and signal 31 is `SIGSYS: bad system call`. So you might need to try using ptrace here to see what's happening.

**Comment by capttrousers** [comment]
Yeah I think I've got a 64 bit kernel but a 32bit userland
https://forums.raspberrypi.com/viewtopic.php?t=317040

Looks like the only way to fix this is a clean OS install which will be this next week's project. I'll be once I clean install a proper 64bit raspbian this will work. 

Thanks for checking this out!
